# Informations générales du site
site_name: 2TL HTB
site_author: 'JeanPiffre'

# Configuration du thème
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.expand
    - navigation.path
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

# Navigation
nav:
  - Accueil: 'index.md'
  - Guide:
    - Méthodologie Web: 'guide/metho_web.md'
  - Outils:
    - Enumération: 
      - Nmap: 'tools/enumeration/nmap.md'
    - Web: 
      - DirB: 'tools/web/dirb.md'
      - Ffuf: 'tools/web/ffuf.md'
      - GoBuster: 'tools/web/gobuster.md'
  - Write Up:
    - HTB: 
      - CozyHosting: 'writeup/htb/CozyHosting.md'

# Extensions Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  
plugins:
  - tags
  